services:
  mongo:
    image: mongodb/mongodb-community-server:8.0.14-rc1-ubi8
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongo-data:/data/db 
    networks:
      - notes-network

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: true
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASSWORD}
    depends_on:
      - mongo 
    networks:
      - notes-network

  notes-api:
    build: .
    image: ${DOCKER_USERNAME}/notes-api:latest
    container_name: notes-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      MONGO_DB_URI: ${MONGO_DB_URI}
    depends_on:
      - mongo
    networks:
      - notes-network


volumes:
  mongo-data:

networks:
  notes-network:
    driver: bridge 

